### ISSUE TITLE
R version 4

### ISSUE THREAD

**Issue by JBreunig** [tk382/HIPPO#1]
Looking forward to trying this but get the error message on install "this R is version 3.6.2, package 'HIPPO' requires R >= 4.0.0".  

Is this correct that it requires 4.0.0 given that 4.0.0 is pre-release?

**Comment by tk382** [comment]
Thank you for your interest! HIPPO is going through a bit of polishing while being reviewed by Bioconductor. Once it is in better shape, I will remove the R version requirement. I will then comment here once again before closing the issue, probably within this week.

**Comment by tk382** [comment]
I lifted the version requirement to R>=3.6.0.
