### ISSUE TITLE
hippo_dimension_reduction error

### ISSUE THREAD

**Issue by howardBDC123** [tk382/HIPPO#13]
Hi
Running sce = hippo_dimension_reduction(sce, method="umap" I got the error "Error in t.default(hippo_object$X[hippo_object$features[[1]]$gene, ]) : argument is not a matrix". 
My sce object is from 10X data for ~11,000 human T cells. I used sce = hippo(sce, 
            feature_method = "zero_inflation", clustering_method = "kmeans", K = 16, 
            outlier_proportion = 0.001) to cluster. 
Can you help?
Thanks

**Comment by lxhuang7** [comment]
That is because your count matrix is a compressed, sparse, column-oriented matrix. You can convert it to normal matrix when creating the SingleCellexpEriment object.

sce <- SingleCellExperiment(assays = list(counts = as.matrix(seu@assays$RNA@counts)))
